# Generated by Django 3.1.2 on 2020-10-08 22:37

import checkin.tracking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nachname')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefonnummer')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-Mail Adresse')),
                ('authenticated', models.BooleanField(blank=True, verbose_name='Identität geprüft')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=checkin.tracking.models.pkgen, max_length=4, unique=True, verbose_name='Raumcode')),
                ('org_number', models.CharField(blank=True, help_text='Speicher XI: X.XX.XXX / Dechanatstraße: K.XX', max_length=30, verbose_name='Raumnummer')),
                ('org_name', models.CharField(blank=True, max_length=255, verbose_name='Raumname / Standort')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Maximalkapazität')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracking.location', verbose_name='Teil von')),
            ],
            options={
                'verbose_name': 'Raum / Standort',
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(choices=[('QR_SCAN', 'Scan eines QR-Codes'), ('USER_MANUAL', 'Manuelle Eingabe durch Nutzer'), ('ADMIN_MANUAL', 'Manuelle Eingabe durch Betreiber'), ('FOREIGN_SCAN', 'Scan eines QR-Codes durch andere Person'), ('IMPORT', 'Datenimport')], default='QR_SCAN', max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.location')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.profile')),
            ],
        ),
    ]
