# Generated by Django 3.1.2 on 2020-10-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Raum / Standort', 'verbose_name_plural': 'Räume / Standorte'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='authenticated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Identität geprüft'),
        ),
    ]
