# Generated by Django 3.1.2 on 2020-10-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20201009_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
