# Generated by Django 3.1.2 on 2020-10-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20201009_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='authenticated',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True, verbose_name='Identität geprüft'),
        ),
    ]
