# Generated by Django 3.1.2 on 2020-10-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20201009_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='authenticated',
            new_name='verified',
        ),
    ]
