# Generated by Django 3.1.2 on 2020-10-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20201009_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name': 'Checkin'},
        ),
    ]
