# Generated by Django 3.1.2 on 2020-10-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20201009_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail Adresse'),
        ),
    ]
