# Generated by Django 3.1.2 on 2020-10-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20201010_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='person',
            new_name='profile',
        ),
    ]
