# Generated by Django 3.1.2 on 2020-10-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20201010_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ('-time_entered',), 'verbose_name': 'Checkin'},
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='time',
            new_name='time_entered',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='created_at',
        ),
        migrations.AddField(
            model_name='checkin',
            name='time_left',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='origin',
            field=models.CharField(choices=[('QR_SCAN', 'Scan eines QR-Codes'), ('USER_MANUAL', 'Manuelle Eingabe durch Nutzer'), ('ADMIN_MANUAL', 'Manuelle Eingabe durch Betreiber'), ('FOREIGN_SCAN', 'Scan eines QR-Codes durch andere Person'), ('PARENT_CHECKOUT', 'Checkout durch übergeordnetes Objekt'), ('IMPORT', 'Datenimport')], default='QR_SCAN', max_length=100),
        ),
    ]
