# Generated by Django 3.1.2 on 2020-10-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_auto_20201011_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='origin_entered',
            field=models.CharField(blank=True, choices=[('QR_SCAN', 'Scan eines QR-Codes'), ('USER_MANUAL', 'Manuelle Eingabe durch Nutzer'), ('ADMIN_MANUAL', 'Manuelle Eingabe durch Betreiber'), ('FOREIGN_SCAN', 'Scan eines QR-Codes durch andere Person'), ('PARENT_CHECKOUT', 'Checkout durch übergeordnetes Objekt'), ('IMPORT', 'Datenimport')], max_length=100, null=True, verbose_name='Datenquelle Checkin'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='origin_left',
            field=models.CharField(blank=True, choices=[('QR_SCAN', 'Scan eines QR-Codes'), ('USER_MANUAL', 'Manuelle Eingabe durch Nutzer'), ('ADMIN_MANUAL', 'Manuelle Eingabe durch Betreiber'), ('FOREIGN_SCAN', 'Scan eines QR-Codes durch andere Person'), ('PARENT_CHECKOUT', 'Checkout durch übergeordnetes Objekt'), ('IMPORT', 'Datenimport')], max_length=100, null=True, verbose_name='Datenquelle Checkout'),
        ),
    ]
