# Generated by Django 3.1.2 on 2020-10-13 11:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20201011_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('distance_rule', models.CharField(max_length=50, verbose_name='Mindestabstand')),
                ('other_rules', models.TextField(verbose_name='Regeln, Sonstige Maßnahmen')),
            ],
            options={
                'verbose_name': 'Aktivitätsprofil',
                'verbose_name_plural': 'Aktivitätsprofile',
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Die Telefonnummer benötigt das Format +(XX) XXXXXXXXXXX.', regex='^\\+?1?[\\d ()]{9,15}$')], verbose_name='Telefonnummer'),
        ),
        migrations.CreateModel(
            name='CapacityForActivityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='Maximalkapazität')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.location', verbose_name='Standort')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.activityprofile', verbose_name='Profil')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='activities',
            field=models.ManyToManyField(through='tracking.CapacityForActivityProfile', to='tracking.ActivityProfile', verbose_name='Aktivitätsprofile und Kapazitäten'),
        ),
    ]
