# Generated by Django 3.1.2 on 2020-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_auto_20201013_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacityforactivityprofile',
            options={'verbose_name': 'Aktivitätsprofil und Kapzitäten', 'verbose_name_plural': 'Aktivitätsprofile und Kapzitäten'},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='activities',
            new_name='org_activities',
        ),
        migrations.AddField(
            model_name='location',
            name='org_capacity_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Bemerkung zur Nutzung / Kapazität'),
        ),
        migrations.AddField(
            model_name='location',
            name='org_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Nutzungsarten'),
        ),
        migrations.AddField(
            model_name='location',
            name='org_responsible',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Raumverantwortliche(r)'),
        ),
        migrations.AddField(
            model_name='location',
            name='org_usage',
            field=models.CharField(choices=[('WO', 'Arbeitsraum'), ('TE', 'Unterrichtsraum'), ('MU', 'Musik / Performance')], default='WO', max_length=2),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='distance_rule',
            field=models.CharField(blank=True, default='1,5 m', max_length=50, null=True, verbose_name='Mindestabstand'),
        ),
        migrations.AlterField(
            model_name='capacityforactivityprofile',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Maximalkapazität'),
        ),
        migrations.AlterField(
            model_name='location',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Raumname / Standort'),
        ),
    ]
