# Generated by Django 3.1.2 on 2020-10-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_auto_20201013_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bezeichnung')),
            ],
        ),
        migrations.CreateModel(
            name='LocationUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bezeichnung')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='org_bookable',
            field=models.BooleanField(default=False, verbose_name='Buchbar / Reservierbar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='org_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Anmerkungen'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='org_usage',
        ),
        migrations.AddField(
            model_name='location',
            name='org_book_via',
            field=models.ManyToManyField(to='tracking.BookingMethod', verbose_name='Buchung via'),
        ),
        migrations.AddField(
            model_name='location',
            name='org_usage',
            field=models.ManyToManyField(to='tracking.LocationUsage', verbose_name='Nutzungsarten'),
        ),
    ]
