# Generated by Django 3.1.2 on 2020-10-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_auto_20201013_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='org_book_via',
        ),
        migrations.AddField(
            model_name='location',
            name='org_book_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.bookingmethod', verbose_name='Buchung via'),
        ),
        migrations.AlterField(
            model_name='location',
            name='org_usage',
            field=models.ManyToManyField(blank=True, to='tracking.LocationUsage', verbose_name='Nutzungsarten'),
        ),
    ]
