# Generated by Django 3.1.2 on 2020-10-13 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_auto_20201013_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_checkin',
        ),
        migrations.AddField(
            model_name='location',
            name='org_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Größe in Quadratmetern'),
        ),
        migrations.AlterField(
            model_name='location',
            name='org_name',
            field=models.CharField(max_length=255, verbose_name='Raumname / Standort'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail Adresse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Die Telefonnummer benötigt das Format +(XX) XXXXXXXXXXX.', regex='^\\+?1?[\\d ()]{9,15}$')], verbose_name='Telefonnummer'),
        ),
    ]
