# Generated by Django 3.1.2 on 2020-10-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_auto_20201014_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='distance_rule_de',
            field=models.CharField(blank=True, default='1,5 m', max_length=50, null=True, verbose_name='Mindestabstand DE'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='distance_rule_en',
            field=models.CharField(blank=True, default='1,5 m', max_length=50, null=True, verbose_name='Mindestabstand EN'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='name_de',
            field=models.CharField(max_length=255, verbose_name='Bezeichnung DE'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Bezeichnung EN'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='other_rules_de',
            field=models.TextField(blank=True, null=True, verbose_name='Regeln, Sonstige Maßnahmen DE'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='other_rules_en',
            field=models.TextField(blank=True, null=True, verbose_name='Regeln, Sonstige Maßnahmen EN'),
        ),
    ]
