# Generated by Django 3.1.2 on 2020-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_auto_20201015_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacityforactivityprofile',
            name='comment_de',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Zusatz DE'),
        ),
        migrations.AddField(
            model_name='capacityforactivityprofile',
            name='comment_en',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Zusatz EN'),
        ),
    ]
