# Generated by Django 3.1.2 on 2020-10-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0023_auto_20201015_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='hide_load',
            field=models.BooleanField(default=False, verbose_name='Checkins verstecken'),
        ),
    ]
