# Generated by Django 3.1.2 on 2020-10-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0025_auto_20201015_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.location', verbose_name='Standort'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.profile', verbose_name='Person'),
        ),
    ]
