# Generated by Django 3.1.2 on 2020-10-23 11:33

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0026_auto_20201016_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.location', verbose_name='Standort'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='origin_entered',
            field=models.CharField(blank=True, choices=[('QR_SCAN', 'Scan eines QR-Codes'), ('USER_MANUAL', 'Manuelle Eingabe durch Nutzer'), ('ADMIN_MANUAL', 'Manuelle Eingabe durch Betreiber'), ('FOREIGN_SCAN', 'Scan eines QR-Codes durch andere Person'), ('PARENT_CHECKIN', 'Checkin durch untergeordnetes Objekt'), ('PARENT_CHECKOUT', 'Checkout durch übergeordnetes Objekt'), ('IMPORT', 'Datenimport')], max_length=100, null=True, verbose_name='Datenquelle Checkin'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='origin_left',
            field=models.CharField(blank=True, choices=[('QR_SCAN', 'Scan eines QR-Codes'), ('USER_MANUAL', 'Manuelle Eingabe durch Nutzer'), ('ADMIN_MANUAL', 'Manuelle Eingabe durch Betreiber'), ('FOREIGN_SCAN', 'Scan eines QR-Codes durch andere Person'), ('PARENT_CHECKIN', 'Checkin durch untergeordnetes Objekt'), ('PARENT_CHECKOUT', 'Checkout durch übergeordnetes Objekt'), ('IMPORT', 'Datenimport')], max_length=100, null=True, verbose_name='Datenquelle Checkout'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.profile', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time_entered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Checkin'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracking.location', verbose_name='Teil von'),
        ),
    ]
