# Generated by Django 3.1.2 on 2020-10-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0029_auto_20201023_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Registrierung'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Letzte Änderung'),
        ),
        migrations.AlterField(
            model_name='location',
            name='org_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in Quadratmetern', max_digits=8, null=True, verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrierung'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Letzte Änderung'),
        ),
    ]
