# Generated by Django 3.1.2 on 2020-10-28 16:59

import checkin.tracking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0031_auto_20201028_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=checkin.tracking.models.pkgen, max_length=4, verbose_name='Raumcode')),
                ('org_number', models.CharField(blank=True, help_text='Speicher XI: X.XX.XXX / Dechanatstraße: K.XX', max_length=30, verbose_name='Raumnummer')),
                ('org_name', models.CharField(max_length=255, verbose_name='Raumname / Standort')),
                ('org_responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='Raumverantwortliche(r)')),
                ('org_size', models.DecimalField(blank=True, decimal_places=2, help_text='in Quadratmetern', max_digits=8, null=True, verbose_name='Größe')),
                ('org_comment', models.TextField(blank=True, null=True, verbose_name='Anmerkungen')),
                ('org_capacity_comment', models.TextField(blank=True, null=True, verbose_name='Bemerkung zur Nutzung / Kapazität')),
                ('org_bookable', models.BooleanField(verbose_name='Buchbar / Reservierbar')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Letzte Änderung')),
                ('hide_load', models.BooleanField(default=False, verbose_name='Checkins verstecken')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org_book_via', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.bookingmethod', verbose_name='Buchung via')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, default=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.location', verbose_name='Teil von')),
            ],
            options={
                'verbose_name': 'historical Raum / Standort',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
