# Generated by Django 3.1.3 on 2020-11-06 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0033_auto_20201104_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ('-time_entered',), 'permissions': [('can_evaluate_case', 'Kann Nachverfolgung durchführen.')], 'verbose_name': 'Checkin'},
        ),
    ]
