# Generated by Django 3.1.3 on 2020-11-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0034_auto_20201107_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='org_number',
            field=models.CharField(blank=True, help_text='Speicher XI: X.XX.XXX / Dechanatstraße: K.XX', max_length=24, verbose_name='Raumnummer'),
        ),
        migrations.AlterField(
            model_name='location',
            name='org_number',
            field=models.CharField(blank=True, help_text='Speicher XI: X.XX.XXX / Dechanatstraße: K.XX', max_length=24, verbose_name='Raumnummer'),
        ),
    ]
