# Generated by Django 3.1.3 on 2020-11-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0035_auto_20201113_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ('-time_entered',), 'permissions': [('can_evaluate_case', 'Kann Nachverfolgung durchführen')], 'verbose_name': 'Checkin'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': [('can_print_location', 'Kann PDF-Raumausweise erstellen'), ('can_display_location_loads', 'Kann aktuelle aktuelle Checkins anzeigen')], 'verbose_name': 'Raum / Standort', 'verbose_name_plural': 'Räume / Standorte'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_all_users', 'Kann alle Personen anzeigen')], 'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
    ]
