# Generated by Django 3.1.5 on 2021-01-20 18:29

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0036_auto_20201118_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='org_alternative_name',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Alternative Bezeichnungen'),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='org_floor_number',
            field=models.IntegerField(blank=True, help_text='-1: Keller, 0: Erdgeschoss, 1: Erste Etage, usw.', null=True, verbose_name='Etage'),
        ),
        migrations.AddField(
            model_name='location',
            name='org_alternative_name',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Alternative Bezeichnungen'),
        ),
        migrations.AddField(
            model_name='location',
            name='org_floor_number',
            field=models.IntegerField(blank=True, help_text='-1: Keller, 0: Erdgeschoss, 1: Erste Etage, usw.', null=True, verbose_name='Etage'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='org_name',
            field=models.CharField(help_text='Bezeichung laut Raumschild.', max_length=255, verbose_name='Raumname / Standort'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='org_number',
            field=models.CharField(blank=True, help_text='Speicher XI: X.XX.XXX / Dechanatstraße: X.XX(x) Mehrere Raumnummern mit / trennen.', max_length=24, verbose_name='Raumnummer'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, db_constraint=False, default=260, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.location', verbose_name='Teil von'),
        ),
        migrations.AlterField(
            model_name='location',
            name='org_name',
            field=models.CharField(help_text='Bezeichung laut Raumschild.', max_length=255, verbose_name='Raumname / Standort'),
        ),
        migrations.AlterField(
            model_name='location',
            name='org_number',
            field=models.CharField(blank=True, help_text='Speicher XI: X.XX.XXX / Dechanatstraße: X.XX(x) Mehrere Raumnummern mit / trennen.', max_length=24, verbose_name='Raumnummer'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=260, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracking.location', verbose_name='Teil von'),
        ),
    ]
