# Generated by Django 3.1.4 on 2020-12-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0036_auto_20201118_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrikelnummer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrikelnummer'),
        ),
    ]
