# Generated by Django 3.1.4 on 2020-12-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0037_add_matrikelnummer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_changes', models.BooleanField(default=False, verbose_name='Änderungen speichern')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Nachname')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefonnummer')),
                ('student_number', models.CharField(blank=True, max_length=20, verbose_name='Matrikelnummer')),
                ('date', models.DateField(verbose_name='Datum')),
                ('signed', models.BooleanField(verbose_name='Unterschrift vorhanden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.profile', verbose_name='Suche')),
            ],
            options={
                'verbose_name': 'Manuelle Besuchsdokumentation',
                'verbose_name_plural': 'Manuelle Besuchsdokumentationen',
            },
        ),
        migrations.CreateModel(
            name='PaperCheckin',
            fields=[
                ('checkin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.checkin')),
                ('location_comment', models.CharField(blank=True, max_length=255, verbose_name='persönliche Referenz')),
                ('log', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tracking.paperlog')),
            ],
            options={
                'verbose_name': 'Manuell eingegebener Aufenthalt',
                'verbose_name_plural': 'Manuell eingegebene Aufenthalte',
            },
            bases=('tracking.checkin',),
        ),
    ]
