# Generated by Django 3.1.5 on 2021-01-11 00:46

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0037_add_matrikelnummer'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='checkin',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time_entered',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Checkin'),
        ),
    ]
