# Generated by Django 3.1.7 on 2021-02-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transfer_profile_to_users_app'),
        ('tracking', '0037_auto_20210110_1534'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='user',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='checkin',
                    name='profile',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.profile', verbose_name='Person'),
                ),
            ],
            # Table already exists. checkin/tracking/migrations/0038_transfer_profile_to_users_app.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='HistoricalProfile',
                ),
                migrations.DeleteModel(
                    name='Profile',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='HistoricalProfile',
                    table='users_historicalprofile',
                ),
                migrations.AlterModelTable(
                    name='Profile',
                    table='users_profile',
                ),
            ]
        )
    ]
