# Generated by Django 3.1.5 on 2021-01-11 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0038_auto_20210111_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Nachname')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefonnummer')),
                ('student_number', models.CharField(blank=True, max_length=20, verbose_name='Matrikelnummer')),
                ('date', models.DateField(help_text='Ohne Datum ist die Eingabe und Kontaktnachverfolgung nicht möglich. Bitte stellen Sie anderweitig Nachforschungen an, falls das Datum fehlt oder unlesbar ist, und wiederholen Sie dann die Eingabe.<br/>Alle Zeitangaben werden in Ihrer Zeitzone (Europe/Berlin) interpretiert.', verbose_name='Datum')),
                ('signed', models.BooleanField(verbose_name='Unterschrift vorhanden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingegeben am')),
                ('comment', models.TextField(blank=True, help_text='Nutzen die dieses Feld für alle weiteren Bemerkugen zum vorliegenden Papierprotokoll oder zu Ihrer Eingabe.', null=True, verbose_name='Kommentar')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.profile', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Manuelle Besuchsdokumentation',
                'verbose_name_plural': 'Manuelle Besuchsdokumentationen',
            },
        ),
        migrations.CreateModel(
            name='PaperCheckin',
            fields=[
                ('checkin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.checkin')),
                ('location_comment', models.CharField(blank=True, max_length=255, verbose_name='persönliche Referenz')),
                ('entered_after_midnight', models.BooleanField(blank=True, verbose_name='Eingang nach 23:59 (Folgetag)')),
                ('left_after_midnight', models.BooleanField(blank=True, verbose_name='Ausgang nach 23:59 (Folgetag)')),
                ('log', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tracking.paperlog')),
            ],
            options={
                'verbose_name': 'Manuell eingegebener Aufenthalt',
                'verbose_name_plural': 'Manuell eingegebene Aufenthalte',
            },
            bases=('tracking.checkin',),
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
    ]
