# Generated by Django 3.1.4 on 2020-12-03 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0038_papercheckin_paperlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperlog',
            name='save_changes',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time_entered',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Checkin'),
        ),
        migrations.AlterField(
            model_name='paperlog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.profile', verbose_name='Person'),
        ),
    ]
