# Generated by Django 3.1.5 on 2021-01-10 22:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0039_auto_20201203_1734'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='papercheckin',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='paperlog',
            name='comment',
            field=models.TextField(blank=True, help_text='Nutzen die dieses Feld für alle weiteren Bemerkugen zum vorliegenden Papierprotokoll oder zu Ihrer Eingabe.', verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='paperlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eingegeben am'),
        ),
        migrations.AlterField(
            model_name='paperlog',
            name='date',
            field=models.DateField(help_text='Ohne Datum ist die Eingabe und Kontaktnachverfolgung nicht möglich. Bitte stellen Sie anderweitig Nachforschungen an, falls das Datum fehlt oder unlesbar ist, und wiederholen Sie dann die Eingabe.', verbose_name='Datum'),
        ),
    ]
