# Generated by Django 3.1.5 on 2021-01-19 12:57

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0039_papercheckin_paperlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papercheckin',
            options={'ordering': ('pk',), 'verbose_name': 'Manuell eingegebener Aufenthalt', 'verbose_name_plural': 'Manuell eingegebene Aufenthalte'},
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='org_alternative_name',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Alternative Bezeichnungen'),
        ),
        migrations.AddField(
            model_name='location',
            name='org_alternative_name',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='Alternative Bezeichnungen'),
        ),
        migrations.AlterField(
            model_name='paperlog',
            name='comment',
            field=models.TextField(blank=True, help_text='Nutzen die dieses Feld für alle weiteren Bemerkugen zum vorliegenden Papierprotokoll oder zu Ihrer Eingabe.', null=True, verbose_name='Eingabekommentar'),
        ),
    ]
