# Generated by Django 3.1.5 on 2021-01-20 10:24

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0040_auto_20210119_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='org_floor_number',
            field=models.IntegerField(blank=True, help_text='-1: Keller, 0: Erdgeschoss, 1: Erste Etage, usw.', null=True, verbose_name='Etage'),
        ),
        migrations.AddField(
            model_name='location',
            name='org_floor_number',
            field=models.IntegerField(blank=True, help_text='-1: Keller, 0: Erdgeschoss, 1: Erste Etage, usw.', null=True, verbose_name='Etage'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, db_constraint=False, default=260, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.location', verbose_name='Teil von'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=260, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracking.location', verbose_name='Teil von'),
        ),
    ]
