# Generated by Django 3.1.5 on 2021-01-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0040_auto_20210110_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperlog',
            name='comment',
            field=models.TextField(blank=True, help_text='Nutzen die dieses Feld für alle weiteren Bemerkugen zum vorliegenden Papierprotokoll oder zu Ihrer Eingabe.', null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='paperlog',
            name='date',
            field=models.DateField(help_text='Ohne Datum ist die Eingabe und Kontaktnachverfolgung nicht möglich. Bitte stellen Sie anderweitig Nachforschungen an, falls das Datum fehlt oder unlesbar ist, und wiederholen Sie dann die Eingabe.<br/>Alle Zeitangaben werden in Ihrer Zeitzone Europe/Berlin interpretiert.', verbose_name='Datum'),
        ),
    ]
