# Generated by Django 3.1.5 on 2021-02-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0040_auto_20210202_1426'),
        ('tracking', '0037_auto_20210120_1929'),
    ]

    operations = [
    ]
