# Generated by Django 3.1.5 on 2021-01-11 00:24

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0041_auto_20210110_2357'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='checkin',
            managers=[
                ('all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='papercheckin',
            name='entered_after_midnight',
            field=models.BooleanField(blank=True, default=False, verbose_name='Eingang nach 23:59 (Folgetag)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papercheckin',
            name='left_after_midnight',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ausgang nach 23:59 (Folgetag)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperlog',
            name='date',
            field=models.DateField(help_text='Ohne Datum ist die Eingabe und Kontaktnachverfolgung nicht möglich. Bitte stellen Sie anderweitig Nachforschungen an, falls das Datum fehlt oder unlesbar ist, und wiederholen Sie dann die Eingabe.<br/>Alle Zeitangaben werden in Ihrer Zeitzone (Europe/Berlin) interpretiert.', verbose_name='Datum'),
        ),
    ]
