# Generated by Django 3.1.5 on 2021-01-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0041_auto_20210120_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='org_name',
            field=models.CharField(help_text='Bezeichung laut Raumschild.', max_length=255, verbose_name='Raumname / Standort'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='org_number',
            field=models.CharField(blank=True, help_text='Speicher XI: X.XX.XXX / Dechanatstraße: X.XX(x) Mehrere Raumnummern mit / trennen.', max_length=24, verbose_name='Raumnummer'),
        ),
        migrations.AlterField(
            model_name='location',
            name='org_name',
            field=models.CharField(help_text='Bezeichung laut Raumschild.', max_length=255, verbose_name='Raumname / Standort'),
        ),
        migrations.AlterField(
            model_name='location',
            name='org_number',
            field=models.CharField(blank=True, help_text='Speicher XI: X.XX.XXX / Dechanatstraße: X.XX(x) Mehrere Raumnummern mit / trennen.', max_length=24, verbose_name='Raumnummer'),
        ),
    ]
