# Generated by Django 3.1.5 on 2021-01-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0036_auto_20201118_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_all_users', 'Kann alle Personen anzeigen'), ('can_view_real_names', 'Kann Klarnamen anzeigen'), ('can_view_full_email', 'Kann vollständige E-Mail-Adresse anzeigen'), ('can_view_full_phone_number', 'Kann vollständige Telefonnummer anzeigen')], 'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
    ]
