# Generated by Django 3.1.7 on 2021-03-14 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_merging_resources_with_checkin_locations'),
        ('tracking', '0052_checkin_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='resource',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkinlocation', to='resources.resource'),
        ),
    ]
