# Generated by Django 3.1.7 on 2021-03-03 18:06

from django.db import migrations, models
import django.db.models.deletion

from checkin.resources.management.commands.resources_import_from_locations import create_resource_from_location

def transfer_checkin_locations_to_resources(apps, schema_editor):
    from checkin.tracking.legacy import Location
    db_alias = schema_editor.connection.alias
    # Type = apps.get_model("core", "Type")
    # Type.objects.using(db_alias).create(property=value)
    qs = Location.objects.using(db_alias).all()
    resources = [create_resource_from_location(location, using=db_alias) for location in qs]
    print('Successfully created %i objects.' % len(resources))

class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0053_add_resource_relation_location'),
    ]

    operations = [
        migrations.RunPython(transfer_checkin_locations_to_resources),
    ]
