# Generated by Django 3.1.7 on 2021-03-13 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_auto_20210313_0255'),
        ('tracking', '0053_merging_resources_with_checkin_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='resource',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkinlocation', to='resources.resource'),
        ),
    ]
