# Generated by Django 3.1.7 on 2021-03-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0054_merging_resources_with_checkin_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='org_book_via',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='parent',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': [('can_print_location', 'Kann PDF-Raumausweise erstellen'), ('can_display_location_loads', 'Kann aktuelle aktuelle Checkins anzeigen')], 'verbose_name': 'Checkin-Standort', 'verbose_name_plural': 'Checkin-Standorte'},
        ),
        migrations.RemoveConstraint(
            model_name='checkin',
            name='tracking_checkin_origins_valid',
        ),
        migrations.RemoveField(
            model_name='location',
            name='org_book_via',
        ),
        migrations.RemoveField(
            model_name='location',
            name='org_bookable',
        ),
        migrations.RemoveField(
            model_name='location',
            name='org_capacity_comment',
        ),
        migrations.RemoveField(
            model_name='location',
            name='org_comment',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='org_name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='org_number',
            new_name='_number',
        ),
        migrations.RemoveField(
            model_name='location',
            name='org_responsible',
        ),
        migrations.RemoveField(
            model_name='location',
            name='org_size',
        ),
        migrations.RemoveField(
            model_name='location',
            name='org_usage',
        ),
        migrations.AddField(
            model_name='location',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.resource'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='origin_entered',
            field=models.CharField(blank=True, choices=[('QR_SCAN', 'Scan eines QR-Codes'), ('USER_MANUAL', 'Manuelle Eingabe durch Nutzer'), ('ADMIN_MANUAL', 'Manuelle Eingabe durch Betreiber'), ('FRONTDESK_MANUAL', 'Manuelle Eingabe durch Empfangspersonal'), ('FOREIGN_SCAN', 'Scan eines QR-Codes durch andere Person'), ('PARENT_CHECKIN', 'Checkin durch untergeordnetes Objekt'), ('PARENT_CHECKOUT', 'Checkout durch übergeordnetes Objekt'), ('IMPORT', 'Import')], max_length=100, null=True, verbose_name='Datenquelle Eingang'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='origin_left',
            field=models.CharField(blank=True, choices=[('QR_SCAN', 'Scan eines QR-Codes'), ('USER_MANUAL', 'Manuelle Eingabe durch Nutzer'), ('ADMIN_MANUAL', 'Manuelle Eingabe durch Betreiber'), ('FRONTDESK_MANUAL', 'Manuelle Eingabe durch Empfangspersonal'), ('FOREIGN_SCAN', 'Scan eines QR-Codes durch andere Person'), ('PARENT_CHECKIN', 'Checkin durch untergeordnetes Objekt'), ('PARENT_CHECKOUT', 'Checkout durch übergeordnetes Objekt'), ('IMPORT', 'Import')], max_length=100, null=True, verbose_name='Datenquelle Ausgang'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time_entered',
            field=models.DateTimeField(verbose_name='Eingang'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='time_left',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ausgang'),
        ),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.CheckConstraint(check=models.Q(('origin_entered__in', ['QR_SCAN', 'USER_MANUAL', 'ADMIN_MANUAL', 'FRONTDESK_MANUAL', 'FOREIGN_SCAN', 'PARENT_CHECKIN', 'PARENT_CHECKOUT', 'IMPORT']), ('origin_left__in', ['QR_SCAN', 'USER_MANUAL', 'ADMIN_MANUAL', 'FRONTDESK_MANUAL', 'FOREIGN_SCAN', 'PARENT_CHECKIN', 'PARENT_CHECKOUT', 'IMPORT'])), name='tracking_checkin_origins_valid'),
        ),
        migrations.DeleteModel(
            name='HistoricalLocation',
        ),
    ]
