# Generated by Django 3.1.7 on 2021-03-15 17:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0055_remove_legacy_model_from_db'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='papercheckin',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='org_alternative_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='org_floor_number',
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='description_de',
            field=models.TextField(verbose_name='Beschreibung DE'),
        ),
        migrations.AlterField(
            model_name='activityprofile',
            name='description_en',
            field=models.TextField(verbose_name='Beschreibung EN'),
        ),
        migrations.AlterField(
            model_name='location',
            name='hide_load',
            field=models.BooleanField(default=False, help_text='Anzahl der aktuell eingecheckten Personen den Nutzern nicht anzeigen. z.B. für Gebäude etc.', verbose_name='Anzahl der Anwesenden verstecken'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracking.location', verbose_name='Teil von'),
        ),
    ]
