# Generated by Django 3.1.7 on 2021-03-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210326_1529'),
        ('tracking', '0057_auto_20210317_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.profile', verbose_name='Userprofile'),
        ),
        migrations.AlterField(
            model_name='paperlog',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.profile', verbose_name='Userprofile'),
        ),
    ]
