# Generated by Django 3.1.5 on 2021-02-16 12:19

import checkin.notifications.template_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_office', '0011_models_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmailTemplate',
            fields=[
                ('emailtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post_office.emailtemplate')),
                ('type', models.CharField(choices=[('reservation_requested', 'Reservation requested'), ('reservation_requested_official', 'Reservation requested official'), ('reservation_cancelled', 'Reservation cancelled'), ('reservation_confirmed', 'Reservation confirmed'), ('reservation_denied', 'Reservation denied'), ('reservation_created', 'Reservation created'), ('reservation_created_with_access_code', 'Reservation created with access code'), ('reservation_access_code_created', 'Reservation reservation_access_code_created'), ('reservation_waiting_for_payment', 'Reservation reservation_waiting_for_payment'), ('reservation_comment_created', 'Reservation comment created')], db_index=True, max_length=100, unique=True, verbose_name='Type')),
                ('template', checkin.notifications.template_field.TemplateField(blank=True, choices=[('notifications/email_important.html', 'Email important'), ('notifications/email_base.html', 'Email base')], display_name=checkin.notifications.template_field.nice_display_name, match='^notifications/.+\\.html$')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['name'],
            },
            bases=('post_office.emailtemplate',),
        ),
    ]
