# Generated by Django 3.1.7 on 2021-03-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_office', '0011_models_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmailTemplate',
            fields=[
                ('emailtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post_office.emailtemplate')),
                ('type', models.CharField(choices=[('reservation_requested', 'Reservation requested'), ('reservation_requested_official', 'Reservation requested to delegtes'), ('reservation_external_user_requested_official', 'External attendee requested to delegtes'), ('reservation_access_requested_official', 'Resource access requested to access delegtes'), ('reservation_cancelled', 'Reservation cancelled'), ('reservation_confirmed', 'Reservation confirmed'), ('reservation_denied', 'Reservation denied'), ('reservation_created', 'Reservation created'), ('reservation_created_with_access_code', 'Reservation created with access code'), ('reservation_access_code_created', 'Reservation reservation_access_code_created'), ('reservation_waiting_for_payment', 'Reservation reservation_waiting_for_payment'), ('reservation_comment_created', 'Reservation comment created')], db_index=True, max_length=100, unique=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Notification template',
                'verbose_name_plural': 'Notification templates',
            },
            bases=('post_office.emailtemplate',),
        ),
    ]
