# Generated by Django 3.1.7 on 2021-02-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210218_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationemailtemplate',
            options={'verbose_name': 'Notification template', 'verbose_name_plural': 'Notification templates'},
        ),
        migrations.AlterField(
            model_name='notificationemailtemplate',
            name='type',
            field=models.CharField(choices=[('reservation_requested', 'Reservation requested'), ('reservation_requested_official', 'Reservation requested official'), ('reservation_cancelled', 'Reservation cancelled'), ('reservation_confirmed', 'Reservation confirmed'), ('reservation_denied', 'Reservation denied'), ('reservation_created', 'Reservation created'), ('reservation_created_with_access_code', 'Reservation created with access code'), ('reservation_access_code_created', 'Reservation reservation_access_code_created'), ('reservation_waiting_for_payment', 'Reservation reservation_waiting_for_payment'), ('reservation_comment_created', 'Reservation comment created')], db_index=True, max_length=100, unique=True, verbose_name='Type'),
        ),
    ]
