# Generated by Django 3.1.7 on 2021-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20210226_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationemailtemplate',
            name='type',
            field=models.CharField(choices=[('reservation_requested', 'Reservation requested'), ('reservation_requested_official', 'Reservation requested to delegtes'), ('reservation_external_user_requested_official', 'External attendee requested to delegtes'), ('reservation_access_requested_official', 'Resource access requested to access delegtes'), ('reservation_cancelled', 'Reservation cancelled'), ('reservation_confirmed', 'Reservation confirmed'), ('reservation_denied', 'Reservation denied'), ('reservation_created', 'Reservation created'), ('reservation_created_with_access_code', 'Reservation created with access code'), ('reservation_access_code_created', 'Reservation reservation_access_code_created'), ('reservation_waiting_for_payment', 'Reservation reservation_waiting_for_payment'), ('reservation_comment_created', 'Reservation comment created')], db_index=True, max_length=100, unique=True, verbose_name='Type'),
        ),
    ]
