# Generated by Django 3.1.5 on 2021-01-08 23:22

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0036_auto_20201118_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, help_text='Speicher XI: X.XX.XXX / Dechanatstraße: K.XX', size=None, verbose_name='Raumnummer(n)')),
                ('name', models.CharField(max_length=255, verbose_name='Raumname')),
                ('room_size', models.DecimalField(blank=True, decimal_places=2, help_text='in Quadratmetern', max_digits=8, null=True, verbose_name='Größe')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Beschreibung / Anmerkungen')),
                ('capacity_comment', models.TextField(blank=True, null=True, verbose_name='Bemerkung zur Nutzung / Einschränkungen / Kapazität')),
                ('bookable', models.BooleanField(verbose_name='Buchbar / Reservierbar')),
                ('access_restricted', models.BooleanField(blank=True, verbose_name='Zugangsbeschränkt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Letzte Änderung')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
            },
        ),
        migrations.CreateModel(
            name='RoomBookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Beginn')),
                ('end', models.DateTimeField(verbose_name='Ende')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Kommentar')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titel / Nutzung')),
                ('is_important', models.BooleanField(blank=True)),
                ('agreed_to_phone_contact', models.BooleanField(blank=True)),
                ('guests', models.ManyToManyField(blank=True, related_name='guest_in_booking', to='tracking.Profile', verbose_name='Zusätzliche Personen')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.profile', verbose_name='Anfragender')),
                ('rooms', models.ManyToManyField(to='booking.Room', verbose_name='Räume')),
            ],
            options={
                'verbose_name': 'Buchungsanfrage',
                'verbose_name_plural': 'Buchungsanfragen',
            },
        ),
        migrations.CreateModel(
            name='RoomAccessPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('ALLOWED', 'ist zugangsberechtigt'), ('DECLINED', 'ist nicht zugangsberechtigt'), ('REQUESTED', 'hat angefragt')], default='ALLOWED', max_length=25, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemerkung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Letzte Änderung')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
            options={
                'verbose_name': 'Zugangsberechtigung',
                'verbose_name_plural': 'Zugangsberechtigungen',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='access_allowd_to',
            field=models.ManyToManyField(related_name='allowed_to_book_in', through='booking.RoomAccessPolicy', to='tracking.Profile', verbose_name='Zugangsberechtigt'),
        ),
        migrations.AddField(
            model_name='room',
            name='book_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.bookingmethod', verbose_name='Buchung via'),
        ),
        migrations.AddField(
            model_name='room',
            name='delegates',
            field=models.ManyToManyField(blank=True, null=True, to='tracking.Profile', verbose_name='Raumverantwortliche(r)'),
        ),
        migrations.AddField(
            model_name='room',
            name='usage',
            field=models.ManyToManyField(blank=True, to='tracking.LocationUsage', verbose_name='Nutzungsarten'),
        ),
    ]
