# Generated by Django 3.1.5 on 2021-01-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0037_auto_20210110_1534'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='delegates',
            field=models.ManyToManyField(to='tracking.Profile', verbose_name='Raumverantwortliche(r)'),
        ),
        migrations.AlterField(
            model_name='roombookingrequest',
            name='agreed_to_phone_contact',
            field=models.BooleanField(blank=True, verbose_name='Telefonkontakt zugestimmt'),
        ),
        migrations.AlterField(
            model_name='roombookingrequest',
            name='guests',
            field=models.ManyToManyField(related_name='guest_in_booking', to='tracking.Profile', verbose_name='Zusätzliche Personen'),
        ),
        migrations.AlterField(
            model_name='roombookingrequest',
            name='is_important',
            field=models.BooleanField(blank=True, help_text='Nur mit Begründung. (Siehe Kommentar.) z.B. Prüfungen, Ausnahmeregelungen, Verasnstaltungen etc. ', verbose_name='Wichtig / Priorisiert'),
        ),
        migrations.AlterField(
            model_name='roombookingrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titel der Nutzung'),
        ),
    ]
