# Generated by Django 3.1.5 on 2021-01-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomaccesspolicy',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='Bis'),
        ),
        migrations.AddField(
            model_name='roomaccesspolicy',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Von'),
        ),
    ]
