# Generated by Django 3.1.5 on 2021-01-10 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210110_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookingrequest',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
