# Generated by Django 3.1.5 on 2021-01-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0037_auto_20210110_1534'),
        ('booking', '0003_roombookingrequest_timerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAccess',
            fields=[
            ],
            options={
                'verbose_name': 'Zugangsberechtigungen',
                'verbose_name_plural': 'Zugangsberechtigungen zu Räumen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.room',),
        ),
        migrations.AlterField(
            model_name='roombookingrequest',
            name='is_important',
            field=models.BooleanField(blank=True, help_text='Nur mit Begründung. (Siehe Kommentar.) z.B. Prüfungen, Ausnahmeregelungen, Verasnstaltungen etc. ', verbose_name='!'),
        ),
        migrations.AlterField(
            model_name='roombookingrequest',
            name='rooms',
            field=models.ManyToManyField(to='booking.Room', verbose_name='Raum'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('WAITING', 'benötigt Genehmigung'), ('CONFIRMED', 'ist genehmigt'), ('DENIED', 'abgelehnt')], max_length=25, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemerkung')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Letzte Änderung')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.profile')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roombookingrequest')),
            ],
            options={
                'verbose_name': 'Teilnahmer',
                'verbose_name_plural': 'Teilnahmer',
            },
        ),
    ]
