# Generated by Django 3.1.5 on 2021-02-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210211_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombookingrequest',
            name='guests',
        ),
    ]
