# Generated by Django 3.1.5 on 2021-02-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0037_auto_20210110_1534'),
        ('booking', '0006_remove_roombookingrequest_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombookingrequest',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='guest_in_booking', through='booking.GuestInRoomBooking', to='tracking.Profile', verbose_name='Zusätzliche Personen'),
        ),
    ]
