/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv from 'ajv';
import Checkin from './Checkin';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));


export const CheckinSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "Pick<default,\"id\"|\"time_entered\"|\"time_left\"|\"location\"|\"is_active\">": {
      "defaultProperties": [
      ],
      "properties": {
        "id": {
          "type": "number"
        },
        "is_active": {
          "type": "boolean"
        },
        "location": {
          "$ref": "#/definitions/default_1"
        },
        "time_entered": {
          "type": "string"
        },
        "time_left": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "id",
        "is_active",
        "location",
        "time_entered",
        "time_left"
      ],
      "type": "object"
    },
    "default": {
      "defaultProperties": [
      ],
      "properties": {
        "display_name": {
          "type": "string"
        },
        "email": {
          "type": [
            "null",
            "string"
          ]
        },
        "first_name": {
          "type": "string"
        },
        "id": {
          "type": "number"
        },
        "keycard_number": {
          "type": [
            "null",
            "string"
          ]
        },
        "keycard_requested_at_at": {
          "anyOf": [
            {
              "description": "Enables basic storage and retrieval of dates and times.",
              "format": "date-time",
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "last_checkins": {
          "items": {
            "$ref": "#/definitions/Pick<default,\"id\"|\"time_entered\"|\"time_left\"|\"location\"|\"is_active\">"
          },
          "type": "array"
        },
        "last_name": {
          "type": "string"
        },
        "phone": {
          "type": [
            "null",
            "string"
          ]
        },
        "preferred_language": {
          "anyOf": [
            {
              "enum": [
                "de",
                "en"
              ],
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "verified": {
          "type": "boolean"
        }
      },
      "required": [
        "display_name",
        "email",
        "first_name",
        "id",
        "keycard_number",
        "keycard_requested_at_at",
        "last_checkins",
        "last_name",
        "phone",
        "preferred_language",
        "verified"
      ],
      "type": "object"
    },
    "default_1": {
      "defaultProperties": [
      ],
      "properties": {
        "capacity": {
          "type": [
            "null",
            "number"
          ]
        },
        "code": {
          "type": "string"
        },
        "id": {
          "type": "number"
        },
        "load": {
          "type": "number"
        },
        "org_name": {
          "type": "string"
        },
        "org_number": {
          "type": "string"
        }
      },
      "required": [
        "capacity",
        "code",
        "id",
        "load",
        "org_name",
        "org_number"
      ],
      "type": "object"
    }
  },
  "properties": {
    "id": {
      "type": "number"
    },
    "is_active": {
      "type": "boolean"
    },
    "location": {
      "$ref": "#/definitions/default_1"
    },
    "profile": {
      "$ref": "#/definitions/default"
    },
    "time_entered": {
      "type": "string"
    },
    "time_left": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  "required": [
    "id",
    "is_active",
    "location",
    "profile",
    "time_entered",
    "time_left"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isCheckin = ajv.compile(CheckinSchema) as ValidateFunction<Checkin>;
export default function validate(value: unknown): Checkin {
  if (isCheckin(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isCheckin.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Checkin'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
