/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv from 'ajv';
import FullCalendarEventOnResource from './FullCalendarEventOnResource';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));


export const FullCalendarEventOnResourceSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "color": {
      "type": "string"
    },
    "display": {
      "enum": [
        "auto",
        "background",
        "block",
        "inverse-background",
        "list-item",
        "none"
      ],
      "type": "string"
    },
    "end": {
      "anyOf": [
        {
          "description": "Enables basic storage and retrieval of dates and times.",
          "format": "date-time",
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "id": {
      "type": "string"
    },
    "identifier": {
      "type": "string"
    },
    "resourceId": {
      "type": "string"
    },
    "start": {
      "anyOf": [
        {
          "description": "Enables basic storage and retrieval of dates and times.",
          "format": "date-time",
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "title": {
      "type": "string"
    }
  },
  "required": [
    "end",
    "start"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isFullCalendarEventOnResource = ajv.compile(FullCalendarEventOnResourceSchema) as ValidateFunction<FullCalendarEventOnResource>;
export default function validate(value: unknown): FullCalendarEventOnResource {
  if (isFullCalendarEventOnResource(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isFullCalendarEventOnResource.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'FullCalendarEventOnResource'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
