/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv from 'ajv';
import Locale from './Locale';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));


export const LocaleSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "enum": [
    "de",
    "en"
  ],
  "type": "string"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isLocale = ajv.compile(LocaleSchema) as ValidateFunction<Locale>;
export default function validate(value: unknown): Locale {
  if (isLocale(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isLocale.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Locale'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
