/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv from 'ajv';
import NewReservation from './NewReservation';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export const NewReservationSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "Pick<default,\"id\"|\"first_name\"|\"last_name\"|\"phone\"|\"verified\">": {
      "defaultProperties": [
      ],
      "properties": {
        "first_name": {
          "type": "string"
        },
        "id": {
          "type": "number"
        },
        "last_name": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "verified": {
          "type": "boolean"
        }
      },
      "required": [
        "first_name",
        "id",
        "last_name",
        "phone",
        "verified"
      ],
      "type": "object"
    },
    "ReservationReason": {
      "enum": [
        0,
        1,
        2,
        3
      ],
      "type": "number"
    },
    "Resource": {
      "defaultProperties": [
      ],
      "type": "object"
    }
  },
  "properties": {
    "agreed_to_phone_contact": {
      "type": "boolean"
    },
    "attendees": {
      "items": {
        "$ref": "#/definitions/Pick<default,\"id\"|\"first_name\"|\"last_name\"|\"phone\"|\"verified\">"
      },
      "type": "array"
    },
    "comment": {
      "type": "string"
    },
    "end": {
      "description": "Enables basic storage and retrieval of dates and times.",
      "format": "date-time",
      "type": "string"
    },
    "exclusive_resource_usage": {
      "type": "boolean"
    },
    "number_of_extra_attendees": {
      "type": "number"
    },
    "reason": {
      "$ref": "#/definitions/ReservationReason"
    },
    "room_uuid": {
      "type": "string"
    },
    "rooms": {
      "items": {
        "$ref": "#/definitions/Resource"
      },
      "type": "array"
    },
    "start": {
      "description": "Enables basic storage and retrieval of dates and times.",
      "format": "date-time",
      "type": "string"
    },
    "total_number_of_attendees": {
      "type": "number"
    }
  },
  "required": [
    "agreed_to_phone_contact",
    "attendees",
    "comment",
    "end",
    "exclusive_resource_usage",
    "number_of_extra_attendees",
    "reason",
    "room_uuid",
    "rooms",
    "start",
    "total_number_of_attendees"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isNewReservation = ajv.compile(NewReservationSchema) as ValidateFunction<NewReservation>;
export default function validate(value: unknown): NewReservation {
  if (isNewReservation(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isNewReservation.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'NewReservation'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
