/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv from 'ajv';
import NewReservation from './NewReservation';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));


export const NewReservationSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "allOf": [
    {
      "$ref": "#/definitions/DeepRemoveNull<Pick<{begin:Date;end:Date;resource_uuid:string;attendees?:Pick<{readonlyprofile_id:never;readonlyuuid:never;readonlyis_external:never;readonlyis_organizer:never;readonlystate:never;readonlydisplay_name:never;first_name:string;last_name:string;},WritableKeys<{readonlyprofile_id:number;readonlyuuid:string;readonlyis_external:boolean;readonlyis_organizer:boolean;readonlystate:\"denied\"|\"requested\"|\"confirmed\"|null;readonlydisplay_name:string;first_name:string;last_name:string;}>>[]|undefined;number_of_extra_attendees?:number|undefined;message?:string|null|undefined;purpose?:\"FOR_EXAM\"|\"FOR_EXAM_PREPARATION\"|\"FOR_COUNCIL_MEETING\"|\"FOR_PICKUP\"|\"FOR_TEACHING\"|\"FOR_APPOINTMENT\"|\"OTHER\"|null|undefined;agreed_to_phone_contact?:boolean|undefined;exclusive_resource_usage?:boolean|undefined;readonlyuuid:never;readonlyidentifier:never;readonlyresource:never;readonlystate:never;readonlystate_verbose:never;readonlyis_own:never;readonlynumber_of_attendees:never;readonlyhas_priority:never;readonlyneed_manual_confirmation:never;readonlycreated_at:never;},\"end\"|\"begin\"|\"resource_uuid\"|\"attendees\"|\"number_of_extra_attendees\"|\"message\"|\"purpose\"|\"agreed_to_phone_contact\"|\"exclusive_resource_usage\"|undefined>>"
    },
    {
      "defaultProperties": [
      ],
      "properties": {
        "templateId": {
          "type": "string"
        }
      },
      "type": "object"
    }
  ],
  "definitions": {
    "DeepRemoveNull<Pick<{begin:Date;end:Date;resource_uuid:string;attendees?:Pick<{readonlyprofile_id:never;readonlyuuid:never;readonlyis_external:never;readonlyis_organizer:never;readonlystate:never;readonlydisplay_name:never;first_name:string;last_name:string;},WritableKeys<{readonlyprofile_id:number;readonlyuuid:string;readonlyis_external:boolean;readonlyis_organizer:boolean;readonlystate:\"denied\"|\"requested\"|\"confirmed\"|null;readonlydisplay_name:string;first_name:string;last_name:string;}>>[]|undefined;number_of_extra_attendees?:number|undefined;message?:string|null|undefined;purpose?:\"FOR_EXAM\"|\"FOR_EXAM_PREPARATION\"|\"FOR_COUNCIL_MEETING\"|\"FOR_PICKUP\"|\"FOR_TEACHING\"|\"FOR_APPOINTMENT\"|\"OTHER\"|null|undefined;agreed_to_phone_contact?:boolean|undefined;exclusive_resource_usage?:boolean|undefined;readonlyuuid:never;readonlyidentifier:never;readonlyresource:never;readonlystate:never;readonlystate_verbose:never;readonlyis_own:never;readonlynumber_of_attendees:never;readonlyhas_priority:never;readonlyneed_manual_confirmation:never;readonlycreated_at:never;},\"end\"|\"begin\"|\"resource_uuid\"|\"attendees\"|\"number_of_extra_attendees\"|\"message\"|\"purpose\"|\"agreed_to_phone_contact\"|\"exclusive_resource_usage\"|undefined>>": {
      "defaultProperties": [
      ],
      "properties": {
        "agreed_to_phone_contact": {
          "type": "boolean"
        },
        "attendees": {
          "items": {
            "$ref": "#/definitions/Pick<{readonlyprofile_id:never;readonlyuuid:never;readonlyis_external:never;readonlyis_organizer:never;readonlystate:never;readonlydisplay_name:never;first_name:string;last_name:string;},WritableKeys<{readonlyprofile_id:number;readonlyuuid:string;readonlyis_external:boolean;readonlyis_organizer:boolean;readonlystate:\"denied\"|\"requested\"|\"confirmed\"|null;readonlydisplay_name:string;first_name:string;last_name:string;}>>"
          },
          "type": "array"
        },
        "begin": {
          "description": "Enables basic storage and retrieval of dates and times.",
          "format": "date-time",
          "type": "string"
        },
        "end": {
          "description": "Enables basic storage and retrieval of dates and times.",
          "format": "date-time",
          "type": "string"
        },
        "exclusive_resource_usage": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        },
        "number_of_extra_attendees": {
          "type": "number"
        },
        "purpose": {
          "enum": [
            "FOR_APPOINTMENT",
            "FOR_COUNCIL_MEETING",
            "FOR_EXAM",
            "FOR_EXAM_PREPARATION",
            "FOR_PICKUP",
            "FOR_TEACHING",
            "OTHER"
          ],
          "type": "string"
        },
        "resource_uuid": {
          "type": "string"
        }
      },
      "required": [
        "begin",
        "end",
        "resource_uuid"
      ],
      "type": "object"
    },
    "Pick<{readonlyprofile_id:never;readonlyuuid:never;readonlyis_external:never;readonlyis_organizer:never;readonlystate:never;readonlydisplay_name:never;first_name:string;last_name:string;},WritableKeys<{readonlyprofile_id:number;readonlyuuid:string;readonlyis_external:boolean;readonlyis_organizer:boolean;readonlystate:\"denied\"|\"requested\"|\"confirmed\"|null;readonlydisplay_name:string;first_name:string;last_name:string;}>>": {
      "defaultProperties": [
      ],
      "properties": {
        "first_name": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        }
      },
      "required": [
        "first_name",
        "last_name"
      ],
      "type": "object"
    }
  }
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isNewReservation = ajv.compile(NewReservationSchema) as ValidateFunction<NewReservation>;
export default function validate(value: unknown): NewReservation {
  if (isNewReservation(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isNewReservation.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'NewReservation'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
