/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv from 'ajv';
import ReservationPurpose from './ReservationPurpose';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));


export const ReservationPurposeSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "enum": [
    "FOR_APPOINTMENT",
    "FOR_COUNCIL_MEETING",
    "FOR_EXAM",
    "FOR_EXAM_PREPARATION",
    "FOR_PICKUP",
    "FOR_TEACHING",
    "OTHER"
  ],
  "type": "string"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isReservationPurpose = ajv.compile(ReservationPurposeSchema) as ValidateFunction<ReservationPurpose>;
export default function validate(value: unknown): ReservationPurpose {
  if (isReservationPurpose(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isReservationPurpose.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'ReservationPurpose'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
