/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv from 'ajv';
import Reservation from './Reservation';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));


export const ReservationSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "Attendance": {
      "defaultProperties": [
      ],
      "properties": {
        "display_name": {
          "type": "string"
        },
        "first_name": {
          "type": "string"
        },
        "is_external": {
          "type": "boolean"
        },
        "is_organizer": {
          "type": "boolean"
        },
        "last_name": {
          "type": "string"
        },
        "profile_id": {
          "type": "number"
        },
        "state": {
          "anyOf": [
            {
              "enum": [
                "confirmed",
                "denied",
                "requested"
              ],
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "uuid": {
          "type": "string"
        }
      },
      "required": [
        "display_name",
        "first_name",
        "is_external",
        "is_organizer",
        "last_name",
        "profile_id",
        "state",
        "uuid"
      ],
      "type": "object"
    },
    "ReservationState": {
      "enum": [
        "cancelled",
        "confirmed",
        "created",
        "denied",
        "requested"
      ],
      "type": "string"
    },
    "default": {
      "defaultProperties": [
      ],
      "properties": {
        "access_allowed_to_current_user": {
          "type": "boolean"
        },
        "access_delegates": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "access_restricted": {
          "type": "boolean"
        },
        "alternative_names": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "area": {
          "type": [
            "null",
            "string"
          ]
        },
        "capacity": {
          "type": [
            "null",
            "number"
          ]
        },
        "description": {
          "type": [
            "null",
            "string"
          ]
        },
        "display_name": {
          "type": "string"
        },
        "display_numbers": {
          "type": [
            "null",
            "string"
          ]
        },
        "features": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ]
        },
        "floor_name": {
          "type": [
            "null",
            "string"
          ]
        },
        "floor_number": {
          "type": [
            "null",
            "number"
          ]
        },
        "name": {
          "type": "string"
        },
        "reservable": {
          "type": "boolean"
        },
        "reservable_max_days_in_advance": {
          "type": [
            "null",
            "number"
          ]
        },
        "reservable_min_days_in_advance": {
          "type": [
            "null",
            "number"
          ]
        },
        "slot_size": {
          "type": [
            "null",
            "string"
          ]
        },
        "unit": {
          "$ref": "#/definitions/default_1"
        },
        "uuid": {
          "type": "string"
        }
      },
      "required": [
        "access_allowed_to_current_user",
        "access_delegates",
        "access_restricted",
        "alternative_names",
        "area",
        "capacity",
        "description",
        "display_name",
        "display_numbers",
        "features",
        "floor_name",
        "floor_number",
        "name",
        "reservable",
        "reservable_max_days_in_advance",
        "reservable_min_days_in_advance",
        "slot_size",
        "unit",
        "uuid"
      ],
      "type": "object"
    },
    "default_1": {
      "defaultProperties": [
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "uuid": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "slug",
        "uuid"
      ],
      "type": "object"
    }
  },
  "properties": {
    "agreed_to_phone_contact": {
      "type": "boolean"
    },
    "attendees": {
      "items": {
        "$ref": "#/definitions/Attendance"
      },
      "type": "array"
    },
    "begin": {
      "description": "Enables basic storage and retrieval of dates and times.",
      "format": "date-time",
      "type": "string"
    },
    "created_at": {
      "description": "Enables basic storage and retrieval of dates and times.",
      "format": "date-time",
      "type": "string"
    },
    "end": {
      "description": "Enables basic storage and retrieval of dates and times.",
      "format": "date-time",
      "type": "string"
    },
    "exclusive_resource_usage": {
      "type": "boolean"
    },
    "has_priority": {
      "type": "boolean"
    },
    "identifier": {
      "type": "string"
    },
    "is_own": {
      "type": "boolean"
    },
    "message": {
      "type": [
        "null",
        "string"
      ]
    },
    "need_manual_confirmation": {
      "type": "boolean"
    },
    "number_of_attendees": {
      "type": "number"
    },
    "number_of_extra_attendees": {
      "type": "number"
    },
    "purpose": {
      "anyOf": [
        {
          "enum": [
            "FOR_APPOINTMENT",
            "FOR_COUNCIL_MEETING",
            "FOR_EXAM",
            "FOR_EXAM_PREPARATION",
            "FOR_PICKUP",
            "FOR_TEACHING",
            "OTHER"
          ],
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "resource": {
      "$ref": "#/definitions/default"
    },
    "resource_uuid": {
      "type": "string"
    },
    "state": {
      "$ref": "#/definitions/ReservationState"
    },
    "state_verbose": {
      "type": "string"
    },
    "uuid": {
      "type": "string"
    }
  },
  "required": [
    "begin",
    "created_at",
    "end",
    "has_priority",
    "identifier",
    "is_own",
    "need_manual_confirmation",
    "number_of_attendees",
    "resource",
    "resource_uuid",
    "state",
    "state_verbose",
    "uuid"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isReservation = ajv.compile(ReservationSchema) as ValidateFunction<Reservation>;
export default function validate(value: unknown): Reservation {
  if (isReservation(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isReservation.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Reservation'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
