# Generated by Django 3.1.7 on 2021-02-24 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='external_reservation_url',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='max_period',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='max_reservations_per_user',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='min_period',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reservable',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reservable_max_days_in_advance',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reservable_min_days_in_advance',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reservation_confirmed_notification_extra',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reservation_info',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reservation_requested_notification_extra',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='slot_size',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'newly created'), ('requested', 'requested'), ('confirmed', 'confirmed'), ('denied', 'denied'), ('cancelled', 'cancelled')], default='created', max_length=32, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='reservation_delegates',
            field=models.ManyToManyField(related_name='resources_unit_reservation_delegated', to=settings.AUTH_USER_MODEL, verbose_name='Buchungsverantwortliche'),
        ),
    ]
