# Generated by Django 3.1.7 on 2021-03-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_migration_to_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinAttendance',
            fields=[
            ],
            options={
                'verbose_name': 'Attendance registration',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.attendance',),
        ),
    ]
