# Generated by Django 3.1.7 on 2021-02-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210224_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='access_allowd_to',
            new_name='access_allowed_to',
        ),
    ]
