# Generated by Django 3.1.7 on 2021-02-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_models_help_text'),
        ('resources', '0003_auto_20210225_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='related_emails',
            field=models.ManyToManyField(to='post_office.Email', verbose_name='Related sent E-Mails'),
        ),
    ]
