# Generated by Django 3.1.7 on 2021-02-26 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0004_reservation_related_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('begin', 'end'), 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AddField(
            model_name='unit',
            name='user_confirmation_delegates',
            field=models.ManyToManyField(blank=True, related_name='resources_unit_user_confirmation_delegated', to=settings.AUTH_USER_MODEL, verbose_name='User confirmation delegates'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='state',
            field=models.CharField(blank=True, choices=[('requested', 'needs approval'), ('confirmed', 'approved'), ('denied', 'denied')], max_length=25, null=True, verbose_name='State'),
        ),
    ]
