# Generated by Django 3.1.7 on 2021-02-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_also_add_user_confirmation_delegates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('begin', 'end'), 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('unit', 'name'), 'permissions': [('resource:can_approve_reservation', 'Can approve reservation'), ('resource:can_make_reservations', 'Can make reservations'), ('resource:can_modify_reservations', 'Can modify reservations'), ('resource:can_ignore_opening_hours', 'Can make reservations outside opening hours'), ('resource:can_view_reservation_access_code', 'Can view reservation access code'), ('resource:can_view_reservation_extra_fields', 'Can view reservation extra fields'), ('resource:can_view_reservation_user', 'Can view reservation user'), ('resource:can_access_reservation_comments', 'Can access reservation comments'), ('resource:can_comment_reservations', 'Can create comments for a reservation'), ('resource:can_view_reservation_catering_orders', 'Can view reservation catering orders'), ('resource:can_modify_reservation_catering_orders', 'Can modify reservation catering orders'), ('resource:can_view_reservation_product_orders', 'Can view reservation product orders'), ('resource:can_modify_paid_reservations', 'Can modify paid reservations'), ('resource:can_bypass_payment', 'Can bypass payment for paid reservations'), ('resource:can_create_staff_event', 'Can create a reservation that is a staff event'), ('resource:can_create_special_type_reservation', 'Can create reservations of a non-normal type'), ('resource:can_bypass_manual_confirmation', 'Can bypass manual confirmation requirement for resources'), ('resource:can_create_reservations_for_other_users', 'Can create reservations for other registered users'), ('resource:can_create_overlapping_reservations', 'Can create overlapping reservations'), ('resource:can_ignore_max_reservations_per_user', 'Can ignore resources max reservations per user rule'), ('resource:can_ignore_max_period', 'Can ignore resources max period rule'), ('resource:can_set_custom_price_for_reservations', 'Can set custom price for individual reservations')], 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'permissions': [('unit:can_approve_reservation', 'Can approve reservation'), ('unit:can_make_reservations', 'Can make reservations'), ('unit:can_modify_reservations', 'Can modify reservations'), ('unit:can_ignore_opening_hours', 'Can make reservations outside opening hours'), ('unit:can_view_reservation_access_code', 'Can view reservation access code'), ('unit:can_view_reservation_extra_fields', 'Can view reservation extra fields'), ('unit:can_view_reservation_user', 'Can view reservation user'), ('unit:can_access_reservation_comments', 'Can access reservation comments'), ('unit:can_comment_reservations', 'Can create comments for a reservation'), ('unit:can_view_reservation_catering_orders', 'Can view reservation catering orders'), ('unit:can_modify_reservation_catering_orders', 'Can modify reservation catering orders'), ('unit:can_view_reservation_product_orders', 'Can view reservation product orders'), ('unit:can_modify_paid_reservations', 'Can modify paid reservations'), ('unit:can_bypass_payment', 'Can bypass payment for paid reservations'), ('unit:can_create_staff_event', 'Can create a reservation that is a staff event'), ('unit:can_create_special_type_reservation', 'Can create reservations of a non-normal type'), ('unit:can_bypass_manual_confirmation', 'Can bypass manual confirmation requirement for resources'), ('unit:can_create_reservations_for_other_users', 'Can create reservations for other registered users'), ('unit:can_create_overlapping_reservations', 'Can create overlapping reservations'), ('unit:can_ignore_max_reservations_per_user', 'Can ignore resources max reservations per user rule'), ('unit:can_ignore_max_period', 'Can ignore resources max period rule'), ('unit:can_set_custom_price_for_reservations', 'Can set custom price for individual reservations')], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
    ]
