# Generated by Django 3.1.7 on 2021-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_add_reservationpurpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
    ]
