# Generated by Django 3.1.7 on 2021-02-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_change_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToResource',
            fields=[
            ],
            options={
                'verbose_name': 'Access Permissions',
                'verbose_name_plural': 'Access Permissions for Spaces',
                'managed': False,
                'proxy': True,
            },
            bases=('resources.resource',),
        ),
    ]
