# Generated by Django 3.1.7 on 2021-02-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_accesstoresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToResource',
        ),
        migrations.CreateModel(
            name='AccessToResource',
            fields=[
            ],
            options={
                'verbose_name': 'Access Permissions',
                'verbose_name_plural': 'Access Permissions for Spaces',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.resource',),
        ),
    ]
