# Generated by Django 3.1.7 on 2021-03-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_add_public_on_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('begin', 'end'), 'permissions': (('is_hardship_case', 'Hardship treatment'),), 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
