# Generated by Django 3.1.7 on 2021-03-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20210319_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('unit', 'name'), 'permissions': [('resource:can_modify_reservations', 'Can modify reservations'), ('resource:can_make_reservations', 'Can make reservations'), ('resource:can_modify_access', 'Can modify access'), ('resource:has_permanent_access', 'Has permanent access'), ('resource:can_view_reservation_user', 'Can view reservation user'), ('resource:can_bypass_manual_confirmation', 'Can bypass manual confirmation requirement for resources'), ('resource:can_create_overlapping_reservations', 'Can create overlapping reservations'), ('resource:can_ignore_max_reservations_per_user', 'Can ignore resources max reservations per user rule'), ('resource:can_ignore_max_period', 'Can ignore resources max period rule')], 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
