# Generated by Django 3.1.7 on 2021-02-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20210226_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAccess',
            fields=[
            ],
            options={
                'verbose_name': 'Access Permissions',
                'verbose_name_plural': 'Access Permissions for Spaces',
                'managed': False,
                'proxy': True,
            },
            bases=('resources.resource',),
        ),
        migrations.DeleteModel(
            name='AccessToResource',
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('unit', 'name'), 'permissions': [('resource:can_modify_reservations', 'Can modify reservations'), ('resource:can_make_reservations', 'Can make reservations'), ('resource:can_modify_access', 'Can give access'), ('resource:has_permanent_access', 'Has permanent access'), ('resource:can_view_reservation_user', 'Can view reservation user'), ('resource:can_bypass_manual_confirmation', 'Can bypass manual confirmation requirement for resources'), ('resource:can_create_overlapping_reservations', 'Can create overlapping reservations'), ('resource:can_ignore_max_reservations_per_user', 'Can ignore resources max reservations per user rule'), ('resource:can_ignore_max_period', 'Can ignore resources max period rule')], 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'permissions': [('unit:can_modify_reservations', 'Can modify reservations'), ('unit:can_confirm_users', 'Can confirm (external) users')], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='access_allowed_to',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='access_delegates',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='reservation_delegates',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='reservation_delegates',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='user_confirmation_delegates',
        ),
    ]
