# Generated by Django 3.1.7 on 2021-03-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20210322_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, help_text='For internal use only.', null=True, verbose_name='Comment'),
        ),
    ]
