# Generated by Django 3.1.7 on 2021-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_add_reservation_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('unit', 'name'), 'permissions': [('resource:can_modify_reservations', 'Can modify reservations'), ('resource:can_modify_access', 'Can modify access'), ('resource:can_make_reservations', 'Can make reservations'), ('resource:has_permanent_access', 'Has permanent access'), ('resource:can_view_reservation_user', 'Can view reservation user'), ('resource:can_bypass_manual_confirmation', 'Can bypass manual confirmation requirement for resources'), ('resource:can_create_overlapping_reservations', 'Can create overlapping reservations'), ('resource:can_ignore_max_reservations_per_user', 'Can ignore resources max reservations per user rule'), ('resource:can_ignore_max_period', 'Can ignore resources max period rule')], 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'permissions': [('unit:can_modify_reservations', 'Can modify reservations'), ('unit:can_modify_access', 'Can modify access'), ('unit:can_confirm_users', 'Can confirm (external) users')], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
    ]
