# Generated by Django 3.1.7 on 2021-03-25 13:48

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('resources', '0013_update_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationUserGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('visible_in_reservation', models.BooleanField(default=True, verbose_name='Show in reservation backend')),
            ],
            options={
                'verbose_name': 'Usergroup for reservations',
                'verbose_name_plural': 'Usergroups for reservations',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
