# Generated by Django 3.1.7 on 2021-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_reservation_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='comments',
            new_name='message',
        ),
    ]
