# Generated by Django 3.1.7 on 2021-03-03 17:13

import checkin.resources.models.resource
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_auto_20210227_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='unit',
            field=models.ForeignKey(default=checkin.resources.models.resource.get_default_unit, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.unit', verbose_name='Unit'),
        ),
    ]
