# Generated by Django 3.1.7 on 2021-03-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_auto_20210326_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('begin', 'end'), 'permissions': (('skip_reservation_notification', 'Do not send notifications for reservations'),), 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
    ]
