# Generated by Django 3.1.7 on 2021-03-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_merging_resources_with_checkin_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', '◯ newly created'), ('requested', '◐ requested'), ('confirmed', '◑ confirmed'), ('denied', '◓ denied'), ('cancelled', '◒ cancelled')], default='created', max_length=32, verbose_name='State'),
        ),
    ]
