# Generated by Django 3.1.7 on 2021-04-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_auto_20210403_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('unit', 'name'), 'permissions': [('resource:can_modify_reservations', 'Can modify reservations'), ('resource:can_modify_access', 'Can modify access'), ('resource:can_modify_reservations_without_notifications', 'Can modify reservations, but do not notify or use as Reply-To'), ('resource:can_modify_access_without_notifications', 'Can modify access, but do not notify or use as Reply-To'), ('resource:notify_for_reservations', 'Receive notifications for reservation requests, but do not allow access to backend'), ('resource:notify_for_access', 'Receive notifications for access requests, but do not allow access to backend'), ('resource:can_make_reservations', 'Can make reservations'), ('resource:has_permanent_access', 'Has permanent access'), ('resource:can_view_reservation_user', 'Can view reservation user'), ('resource:can_bypass_manual_confirmation', 'Can bypass manual confirmation requirement for resources'), ('resource:can_create_overlapping_reservations', 'Can create overlapping reservations'), ('resource:can_ignore_max_reservations_per_user', 'Can ignore resources max reservations per user rule'), ('resource:can_ignore_max_period', 'Can ignore resources max period rule')], 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'permissions': [('unit:can_modify_reservations', 'Can modify reservations'), ('unit:can_modify_access', 'Can modify access'), ('unit:can_modify_reservations_without_notifications', 'Can modify reservations, but do not notify or use as Reply-To'), ('unit:can_modify_access_without_notifications', 'Can modify access, but do not notify or use as Reply-To'), ('unit:notify_for_reservations', 'Receive notifications for reservation requests, but do not allow access to backend'), ('unit:notify_for_access', 'Receive notifications for access requests, but do not allow access to backend'), ('unit:can_confirm_users', 'Can confirm (external) users'), ('unit:view_resource', 'Can view Spaces within Unit'), ('unit:change_resource', 'Can change Spaces within Unit'), ('unit:delete_resource', 'Can delete Spaces within Unit'), ('unit:add_resource', 'Can add Spaces within Unit')], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
    ]
