# Generated by Django 3.1.7 on 2021-04-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_add_permissions_for_notifications_for_user_confirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinattendance',
            options={'default_permissions': ('view', 'change'), 'verbose_name': 'Attendance registration', 'verbose_name_plural': 'Attendance registrations'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='state',
            field=models.CharField(blank=True, choices=[('requested', 'needs approval'), ('confirmed', 'approved'), ('denied', 'denied')], max_length=25, null=True, verbose_name='Attendance state'),
        ),
    ]
