# Generated by Django 3.1.7 on 2021-03-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_auto_20210313_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='need_manual_confirmation',
            field=models.BooleanField(default=True, verbose_name='Need manual confirmation'),
        ),
    ]
