# Generated by Django 3.1.7 on 2021-05-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_auto_20210405_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('created', 'newly created'), ('requested', 'requested'), ('confirmed', 'confirmed'), ('denied', 'denied'), ('cancelled', 'cancelled by user')], default='created', max_length=32, verbose_name='State'),
        ),
    ]
