# Generated by Django 3.1.7 on 2021-03-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_resource_need_manual_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefeature',
            name='name_de',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='resourcefeature',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
