# Generated by Django 3.1.12 on 2021-06-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_auto_20210523_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecapacitypolicy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resourcecapacitypolicy',
            name='resources',
            field=models.ManyToManyField(related_name='capacity_policies', to='resources.Resource', verbose_name='Resources'),
        ),
    ]
