# Generated by Django 3.1.7 on 2021-03-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_auto_20210314_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='people_capacity',
            new_name='people_capacity_default',
        ),
        migrations.AlterField(
            model_name='resource',
            name='people_capacity_default',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Default people capacity'),
        ),
    ]
