# Generated by Django 3.1.12 on 2021-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_auto_20210615_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
