# Generated by Django 3.1.12 on 2021-07-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_reservation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link or web reference for this reservation. e.g. ARTIST page, event annoucement, etc.', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title or reference for events, courses, classes etc.', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
