# Generated by Django 3.1.12 on 2021-08-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_is_general_admin'),
        ('resources', '0026_fix_created_at_on_ModifiableModel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
            ],
            options={
                'verbose_name': 'Resource access permission',
                'verbose_name_plural': 'Resource access permissions',
                'proxy': True,
                'default_permissions': ('view',),
                'indexes': [],
                'constraints': [],
            },
            bases=('users.timeenableduserobjectpermission',),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link or web reference for this reservation. e.g. ARTIST page, event annoucement, etc. (For internal use only.)', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title or reference for events, courses, classes etc. (For internal use only.)', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
