# Generated by Django 3.1.12 on 2021-10-29 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0027_auto_20210807_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEnabledUnitUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt der Erstellung')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zeitpunkt der letzten Änderung')),
                ('synced_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zeitpunkt der Übertragung')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.unit')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeEnabledUnitGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt der Erstellung')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zeitpunkt der letzten Änderung')),
                ('synced_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zeitpunkt der Übertragung')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.unit')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeEnabledResourceUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt der Erstellung')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zeitpunkt der letzten Änderung')),
                ('synced_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zeitpunkt der Übertragung')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeEnabledResourceGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt der Erstellung')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Zeitpunkt der letzten Änderung')),
                ('synced_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zeitpunkt der Übertragung')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
