# Generated by Django 3.1.12 on 2021-10-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_auto_20210807_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='resource',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone extension'),
        ),
    ]
