# Generated by Django 3.1.12 on 2021-10-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0028_auto_20211009_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
    ]
