# Generated by Django 3.1.12 on 2021-10-29 17:36

from django.db import migrations

from checkin.resources.management.commands.resources_convert_to_direct_object_permissions import convert_all

def convert_all_resources_generic_permissions_to_direct_permissions(apps, schema_editor):
    from checkin.tracking.legacy import Location
    db_alias = schema_editor.connection.alias
    # Type = apps.get_model("core", "Type")
    # Type.objects.using(db_alias).create(property=value)
    convert_all(out_method=print, using=db_alias, no_input=True)

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0028_timeenabledresourcegroupobjectpermission_timeenabledresourceuserobjectpermission_timeenabledunitgrou'),
        ('users', '0022_auto_20211029_1824'),
    ]

    operations = [
        migrations.RunPython(convert_all_resources_generic_permissions_to_direct_permissions),
    ]
