# Generated by Django 3.1.12 on 2021-11-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0029_resource_is_public'),
        ('resources', '0029_convert_to_direct_object_permissions'),
    ]

    operations = [
    ]
