# Generated by Django 3.1.12 on 2021-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_merge_20211119_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='automatically_processed',
            field=models.BooleanField(default=False, verbose_name='Initially processed automatically'),
        ),
    ]
