# Generated by Django 3.1.12 on 2022-03-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0031_reservation_automatically_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, help_text='Displayed publicly', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, help_text="Use only if the room has an 'own' email address. Other contacts can be entered as delegates.", max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='need_manual_confirmation',
            field=models.BooleanField(default=True, help_text='If disabled reservation requests will be processed automatically.', verbose_name='Need manual confirmation'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Usually 4 digits. Please do not enter the full phone number.', max_length=20, null=True, verbose_name='Phone extension'),
        ),
    ]
