# Generated by Django 3.1.5 on 2021-02-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_transfer_user_from_django_auth_to_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
