# Generated by Django 3.1.7 on 2021-02-23 19:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_email_as_username'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Profile',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('first_name', models.CharField(max_length=1000, verbose_name='Vorname')),
                        ('last_name', models.CharField(max_length=1000, verbose_name='Nachname')),
                        ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Die Telefonnummer benötigt das Format +(XX) XXXXXXXXXXX.', regex='^\\+?1?[\\d ()]{9,15}$')], verbose_name='Telefonnummer')),
                        ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail Adresse')),
                        ('verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='Identität geprüft')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Letzte Änderung')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrierung')),
                        ('user', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Person',
                        'verbose_name_plural': 'Personen',
                        'permissions': [('can_view_all_users', 'Kann alle Personen anzeigen'), ('can_view_real_names', 'Kann Klarnamen anzeigen'), ('can_view_full_email', 'Kann vollständige E-Mail-Adresse anzeigen'), ('can_view_full_phone_number', 'Kann vollständige Telefonnummer anzeigen')],
                    },
                ),
                migrations.CreateModel(
                    name='HistoricalProfile',
                    fields=[
                        ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                        ('first_name', models.CharField(max_length=1000, verbose_name='Vorname')),
                        ('last_name', models.CharField(max_length=1000, verbose_name='Nachname')),
                        ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Die Telefonnummer benötigt das Format +(XX) XXXXXXXXXXX.', regex='^\\+?1?[\\d ()]{9,15}$')], verbose_name='Telefonnummer')),
                        ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail Adresse')),
                        ('verified', models.BooleanField(blank=True, default=False, null=True, verbose_name='Identität geprüft')),
                        ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Letzte Änderung')),
                        ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registrierung')),
                        ('history_id', models.AutoField(primary_key=True, serialize=False)),
                        ('history_date', models.DateTimeField()),
                        ('history_change_reason', models.CharField(max_length=100, null=True)),
                        ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                        ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                        ('user', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'historical Person',
                        'ordering': ('-history_date', '-history_id'),
                        'get_latest_by': 'history_date',
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
            ],
            # Table already exists. checkin/tracking/migrations/0038_transfer_profile_to_users_app.py
            database_operations=[],
        )
    ]
