# Generated by Django 3.1.7 on 2021-02-23 20:26

import checkin.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transfer_profile_to_users_app'),
        ('tracking', '0051_transfer_profile_to_users_app'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', checkin.users.models.UserManager()),
            ],
        ),
    ]
