# Generated by Django 3.1.7 on 2021-02-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210224_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='is_external',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='External'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_external',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='External'),
        ),
    ]
