# Generated by Django 3.1.7 on 2021-02-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_custom_object_permission_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_general_admin',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
