# Generated by Django 3.1.7 on 2021-03-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_disable_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_any_user', 'Can view any user'), ('can_view_external_users', 'Can view external user'), ('can_view_regular_users', 'Can view regular user'), ('can_view_unverified_users', 'Can view unverified users'), ('can_view_real_names', 'Can view full names'), ('can_view_full_email', 'Can view full e-mail addresses'), ('can_view_full_phone_number', 'Can view full phone numbers')], 'verbose_name': 'Userprofile', 'verbose_name_plural': 'Userprofiles'},
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='verified',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Identität geprüft'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Identität geprüft'),
        ),
    ]
