# Generated by Django 3.1.7 on 2021-05-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_email_to_case_insensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_general_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a administrator with special permissions to many objects within resources application. This is almost as powerful as superuser.', verbose_name='Administrator status (for resources and booking application)'),
        ),
    ]
