# Generated by Django 3.1.13 on 2021-09-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_is_general_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='keycard_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Keycard number'),
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='keycard_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Keycard requested date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='keycard_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Keycard number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='keycard_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Keycard requested date'),
        ),
    ]
