# Generated by Django 3.1.13 on 2021-09-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_synced_at_to_Permission_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_any_user', 'Can view any user or userprofile'), ('can_lookup_any_user', 'Can lookup any user'), ('can_view_external_users', 'Can view external users'), ('can_view_regular_users', 'Can view non-external users'), ('can_view_unverified_users', 'Can view unverified users'), ('can_view_real_names', 'Can display full names'), ('can_view_full_email', 'Can display full e-mail addresses'), ('can_view_full_phone_number', 'Can display full phone numbers'), ('can_view_student_number', 'Can display student numbers'), ('can_change_user_status_only', 'Can change status flags only (!)'), ('can_change_keycard_only', 'Can change keycard only (!)')], 'verbose_name': 'Userprofile', 'verbose_name_plural': 'Userprofiles'},
        ),
    ]
