# Generated by Django 3.1.13 on 2021-09-21 14:07

import checkin.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_synced_at_to_Permission_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_any_user', 'Can view any user or userprofile'), ('can_lookup_any_user', 'Can lookup any user'), ('can_view_external_users', 'Can view external users'), ('can_view_regular_users', 'Can view non-external users'), ('can_view_unverified_users', 'Can view unverified users'), ('can_view_real_names', 'Can display full names'), ('can_view_full_email', 'Can display full e-mail addresses'), ('can_view_full_phone_number', 'Can display full phone numbers'), ('can_view_student_number', 'Can display student numbers'), ('can_change_user_status', 'Can change status'), ('can_change_keycard', 'Can change keycard'), ('can_change_personal_data', 'Can change personal data')], 'verbose_name': 'Userprofile', 'verbose_name_plural': 'Userprofiles'},
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='keycard_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[checkin.users.models.validate_min_length_or_None], verbose_name='Keycard number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='keycard_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[checkin.users.models.validate_min_length_or_None], verbose_name='Keycard number'),
        ),
    ]
