# Generated by Django 3.1.12 on 2021-11-05 16:12

from django.db import migrations, models
from django.db.models import Case, Value, When

def set_is_tempuser_value(apps, schema_editor):
    User = apps.get_model('users', 'user')
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).all().update(
        is_tempuser=Case(
            When(email__startswith='gast-', then=Value(True)),
            When(email__endswith='@gast.hfk-bremen.de', then=Value(True)),
            default=Value(False))
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20211025_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tempuser',
            field=models.BooleanField(default=False, editable=False, verbose_name='Temporary User'),
        ),
        migrations.RunPython(set_is_tempuser_value),
    ]
