# Generated by Django 3.1.12 on 2021-10-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20211025_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeenabledgroupobjectpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt der Erstellung'),
        ),
        migrations.AlterField(
            model_name='timeenabledgroupobjectpermission',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zeitpunkt der letzten Änderung'),
        ),
        migrations.AlterField(
            model_name='timeenabledgroupobjectpermission',
            name='synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zeitpunkt der Übertragung'),
        ),
        migrations.AlterField(
            model_name='timeenableduserobjectpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt der Erstellung'),
        ),
        migrations.AlterField(
            model_name='timeenableduserobjectpermission',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zeitpunkt der letzten Änderung'),
        ),
        migrations.AlterField(
            model_name='timeenableduserobjectpermission',
            name='synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Zeitpunkt der Übertragung'),
        ),
    ]
