# Generated by Django 3.1.12 on 2021-11-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_is_tempuser'),
        ('users', '0022_auto_20211029_1824'),
    ]

    operations = [
    ]
